---
downloads: ~/.ansible-downloads/

homebrew_install_script: "{{ downloads }}/homebrew_install"
homebrew_install_path: /usr/local/bin

homebrew_packages:
- autoconf
- gcc
- gettext
- git
- go
- grep
- htop
- jq
- nvm
- python3
- readline
- wget

homebrew_packages_10_12:
- mysql
- node

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
- chromedriver
- docker
- firefox
- google-chrome
- macvim
- slack
- spotify
- visual-studio-code

homebrew_cask_apps_10_12:
- iterm2

oh_my_zsh_path: ~/.oh-my-zsh

macos_defaults: []

macos_defaults_10_12:
- domain: com.googlecode.iterm2
  key: PrefsCustomFolder
  type: string
  value: "{{ playbook_dir }}/files/iterm2"
- domain: com.googlecode.iterm2
  key: LoadPrefsFromCustomFolder
  type: bool
  value: true
