---
downloads: ~/.ansible-downloads/

homebrew_install_script: "{{ downloads }}/homebrew_install"
homebrew_install_path: /usr/local/bin

homebrew_packages:
- autoconf
- gettext
- git
- go
- grep
- htop
- jq
- mysql
- node
- nvm
- python3
- readline
- wget

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
- chromedriver
- docker
- firefox
- google-chrome
- macvim
- slack

oh_my_zsh_path: ~/.oh-my-zsh
