---
- hosts: all
  connection: local

  vars_files:
  - vars/main.yml

  pre_tasks:
  - block:
    - include_vars: vars/homebrew.yml
    - include_vars: vars/macos.yml
    - include_vars: vars/macos_defaults.yml
    when: ansible_os_family == "Darwin"

  - block:
    - include_vars: vars/arch.yml
    when: ansible_os_family == "Archlinux"

  tasks:
  - include: tasks/ansible-setup.yml
  - include: tasks/dotfiles.yml
    tags:
    - dotfiles

  - block:
    - include: tasks/homebrew.yml
      tags:
      - homebrew
    - include: tasks/macos.yml
    when: ansible_os_family == "Darwin"
    tags:
    - macos

  - include: tasks/arch.yml
    when: ansible_os_family == "Archlinux"
    tags:
    - arch

  - include: tasks/node.yml
  - include: tasks/packages.yml
  - include: tasks/vim.yml
    tags:
    - vim
  - include: tasks/vscode.yml
    tags:
    - vscode
