---
- name: create ansible downloads directory
  file:
    path: "{{ downloads }}"
    state: directory

- name: create ansible config directory
  file:
    path: /etc/ansible
    state: directory
  become: yes
