---
- name: install dotbot
  git:
    repo: https://github.com/anishathalye/dotbot
    dest: "{{ dotbot_path }}"

- name: execute dotbot
  command: "{{ dotbot_bin }} -d {{ playbook_dir }}/files -c {{ dotbot_config | default(dotbot_default_config) }}"

- name: write oh-my-zsh template
  template:
    src: zshrc.oh-my-zsh.j2
    dest: ~/.zshrc.oh-my-zsh
  tags:
  - zsh

- name: set global git config values
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_config_globals }}"

- name: set global git aliases
  git_config:
    name: "alias.{{ item.alias }}"
    value: "{{ item.command }}"
    scope: global
  loop: "{{ git_aliases }}"
