---
- name: install dotbot
  git:
    repo: https://github.com/anishathalye/dotbot
    dest: "{{ dotbot_path }}"

- name: execute dotbot
  command: "{{ dotbot_bin }} -d {{ playbook_dir }}/files -c {{ dotbot_config | default(dotbot_default_config) }}"

- name: write oh-my-zsh template
  template:
    src: zshrc.oh-my-zsh.j2
    dest: ~/.zshrc.oh-my-zsh
  tags:
  - zsh

- name: create vim directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - ~/.vim/autoload
  - ~/.vim/plug
  tags:
  - vim

- name: download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
    mode: 0644
  tags:
  - vim

- name: execute vim-plug install
  command: vim +PlugInstall +qall
  tags:
  - vim
