---
- name: install dotbot
  git:
    repo: https://github.com/anishathalye/dotbot
    dest: "{{ dotbot_path }}"

- name: execute dotbot
  command: "{{ dotbot_bin }} -d {{ playbook_dir }}/files -c {{ dotbot_config | default(dotbot_default_config) }}"

- name: write oh-my-zsh template
  template:
    src: zshrc.oh-my-zsh.j2
    dest: ~/.zshrc.oh-my-zsh
  tags:
  - zsh

- name: create vim pathogen directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
  - ~/.vim/autoload
  - ~/.vim/bundle
  tags:
  - vim

- name: download vim pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
    mode: 0644
  tags:
  - vim
