---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "~/.ssh"

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
  - src: "{{ playbook_dir }}/ssh/config"
    dest: "~/.ssh/config"
