---
- name: install dotbot
  git:
    repo: https://github.com/anishathalye/dotbot
    dest: "{{ dotbot_path }}"

- name: execute dotbot
  command: "{{ dotbot_bin }} -d {{ playbook_dir }}/files -c {{ dotbot_config | default(dotbot_default_config) }}"

- name: generate ssh config
  copy:
    src: ssh/config
    dest: ~/.ssh/config
    force: no

- name: write oh-my-zsh template
  template:
    src: zshrc.oh-my-zsh.j2
    dest: ~/.zshrc.oh-my-zsh
  tags:
  - zsh

- name: set global git config values
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_config_globals | dict2items }}"

- name: set global git aliases
  git_config:
    name: "alias.{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_aliases | dict2items }}"
