---
# Homebrew
- name: download homebrew install script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: "{{ homebrew_install_script }}"
    mode: 0755

- name: install homebrew
  command: "{{ homebrew_install_script }}"
  args:
    creates: "{{ homebrew_install_path }}/brew"

- name: install shells (and update homebrew)
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  loop:
  - bash
  - zsh

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"

- name: install homebrew packages (>= 10.12)
  homebrew:
    name: "{{ item }}"
    state: present
  when: "ansible_distribution_version is version('10.12', '>=')"
  loop: "{{ homebrew_packages_10_12 }}"

- name: install homebrew cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  loop: "{{ homebrew_cask_apps }}"

- name: install homebrew cask apps (>= 10.12)
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  when: "ansible_distribution_version is version('10.12', '>=')"
  loop: "{{ homebrew_cask_apps_10_12 }}"

# Oh-my-zsh
- name: install oh-my-zsh (macos)
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ oh_my_zsh_path }}"

- name: change shell to zsh (macos)
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ homebrew_install_path }}/zsh"
  become: yes

# Fix bash
- name: create user bash_profile (macos)
  file:
    src: "{{ playbook_dir }}/files/sh/.bash_profile"
    dest: ~/.bash_profile
    force: no

# Dots
- name: run dotbot (macos)
  command: "~/.dotbot/bin/dotbot -d {{ playbook_dir }}/files -c {{ playbook_dir }}/files/macos.conf.yaml"

# Set macos defaults
- name: set macos defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    state: present
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ macos_defaults }}"
  loop_control:
    label: "{{ item.key }}"

- name: set macos defaults (>= 10.12)
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    state: present
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ macos_defaults_10_12 }}"
  loop_control:
    label: "{{ item.key }}"
