---
- name: install nvm
  git:
    repo: https://github.com/creationix/nvm
    dest: "{{ nvm_path }}"
  tags:
  - nvm

- name: install node lts
  command: "{{ nvm_path }}/nvm-exec install --lts"
  tags:
  - nvm

- name: alias default node
  command: "{{ nvm_path }}/nvm-exec alias default node"
  tags:
  - nvm
