---
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pip_packages }}"
  tags:
  - pip

- name: install npm packages
  npm:
    name: "{{ item }}"
    executable: "{{ nvm_npm.stdout_lines[-1] }}"
    global: yes
    state: present
  loop: "{{ npm_packages }}"
  tags:
  - npm
