---
downloads: ~/.ansible-downloads/

dotbot_path: ~/.dotbot
dotbot_bin: "{{ dotbot_path }}/bin/dotbot"
dotbot_default_config: "{{ playbook_dir }}/files/arch.conf.yml"

oh_my_zsh_path: ~/.oh-my-zsh
oh_my_zsh_theme: bleblanc
oh_my_zsh_plugins:
- aws
- git
- shrink-path

git_config_globals:
- name: user.name
  value: Brian LeBlanc
- name: fetch.prune
  value: 'true'
- name: push.followTags
  value: 'true'
- name: log.mailmap
  value: 'true'
- name: pull.rebase
  value: 'true'
- name: stash.showPatch
  value: 'true'

git_aliases:
- alias: a
  command: add .
- alias: s
  command: status
- alias: st
  command: status
- alias: co
  command: checkout
- alias: br
  command: branch
- alias: c
  command: commit
- alias: ci
  command: commit
- alias: unstage
  command: reset HEAD --
- alias: get
  command: clone
- alias: root
  command: rev-parse --show-toplevel
- alias: lol
  command: log --graph --oneline
- alias: lola
  command: log --graph --oneline --all
- alias: in
  command: fetch --all
- alias: out
  command: push
- alias: outf
  command: push --force-with-lease
- alias: good
  command: bisect good
- alias: bad
  command: bisect bad

nvm_path: ~/.nvm

pip_packages:
# - awscli # v2 isn't getting published on pip because apparently that's too easy
- boto3
- pep8
- pylint
- pytz
- pyyaml
- requests
- six
- sshuttle
- troposphere
- virtualenv

npm_packages:
- create-react-app
- eslint
- gulp
- serverless
- vim-node-rpc
- yarn

gem_packages:
- rake

vscode_extensions:
- dbaeumer.vscode-eslint
- eamodio.gitlens
- felipecaputo.git-project-manager
- formulahendry.auto-rename-tag
- github.vscode-pull-request-github
- golang.Go
- hashicorp.terraform
- James-Yu.latex-workshop
- kesmarag.base16-tomorrow-night
- ms-azuretools.vscode-docker
- ms-python.python
- msjsdiag.debugger-for-chrome
- rebornix.ruby
- redhat.vscode-yaml
- Tyriar.sort-lines
- vscode-icons-team.vscode-icons
- wholroyd.jinja
